name: t2i-lab4
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - accelerate
      - diffusers>=0.30.0
      - huggingface-hub
      - pillow
      - safetensors
      - torch
      - torchvision
      - transformers
      - -e .
